// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_META_META_H_
#define FLATBUFFERS_GENERATED_META_META_H_

#include "flatbuffers/flatbuffers.h"

namespace meta {

struct User;
struct UserT;

struct Site;
struct SiteT;

struct Data;
struct DataT;

struct UserT : public flatbuffers::NativeTable {
  typedef User TableType;
  std::string name;
  std::string username;
  std::string mac;
  uint8_t site;
  UserT()
      : site(0) {
  }
};

struct User FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UserT NativeTableType;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_USERNAME = 6,
    VT_MAC = 8,
    VT_SITE = 10
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *username() const {
    return GetPointer<const flatbuffers::String *>(VT_USERNAME);
  }
  const flatbuffers::String *mac() const {
    return GetPointer<const flatbuffers::String *>(VT_MAC);
  }
  uint8_t site() const {
    return GetField<uint8_t>(VT_SITE, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_USERNAME) &&
           verifier.VerifyString(username()) &&
           VerifyOffset(verifier, VT_MAC) &&
           verifier.VerifyString(mac()) &&
           VerifyField<uint8_t>(verifier, VT_SITE) &&
           verifier.EndTable();
  }
  UserT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(UserT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<User> Pack(flatbuffers::FlatBufferBuilder &_fbb, const UserT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct UserBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(User::VT_NAME, name);
  }
  void add_username(flatbuffers::Offset<flatbuffers::String> username) {
    fbb_.AddOffset(User::VT_USERNAME, username);
  }
  void add_mac(flatbuffers::Offset<flatbuffers::String> mac) {
    fbb_.AddOffset(User::VT_MAC, mac);
  }
  void add_site(uint8_t site) {
    fbb_.AddElement<uint8_t>(User::VT_SITE, site, 0);
  }
  explicit UserBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  UserBuilder &operator=(const UserBuilder &);
  flatbuffers::Offset<User> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<User>(end);
    return o;
  }
};

inline flatbuffers::Offset<User> CreateUser(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> username = 0,
    flatbuffers::Offset<flatbuffers::String> mac = 0,
    uint8_t site = 0) {
  UserBuilder builder_(_fbb);
  builder_.add_mac(mac);
  builder_.add_username(username);
  builder_.add_name(name);
  builder_.add_site(site);
  return builder_.Finish();
}

inline flatbuffers::Offset<User> CreateUserDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *username = nullptr,
    const char *mac = nullptr,
    uint8_t site = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto username__ = username ? _fbb.CreateString(username) : 0;
  auto mac__ = mac ? _fbb.CreateString(mac) : 0;
  return meta::CreateUser(
      _fbb,
      name__,
      username__,
      mac__,
      site);
}

flatbuffers::Offset<User> CreateUser(flatbuffers::FlatBufferBuilder &_fbb, const UserT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SiteT : public flatbuffers::NativeTable {
  typedef Site TableType;
  std::string name;
  std::string shortname;
  SiteT() {
  }
};

struct Site FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SiteT NativeTableType;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_SHORTNAME = 6
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *shortname() const {
    return GetPointer<const flatbuffers::String *>(VT_SHORTNAME);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_SHORTNAME) &&
           verifier.VerifyString(shortname()) &&
           verifier.EndTable();
  }
  SiteT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SiteT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Site> Pack(flatbuffers::FlatBufferBuilder &_fbb, const SiteT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SiteBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Site::VT_NAME, name);
  }
  void add_shortname(flatbuffers::Offset<flatbuffers::String> shortname) {
    fbb_.AddOffset(Site::VT_SHORTNAME, shortname);
  }
  explicit SiteBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SiteBuilder &operator=(const SiteBuilder &);
  flatbuffers::Offset<Site> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Site>(end);
    return o;
  }
};

inline flatbuffers::Offset<Site> CreateSite(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> shortname = 0) {
  SiteBuilder builder_(_fbb);
  builder_.add_shortname(shortname);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<Site> CreateSiteDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *shortname = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto shortname__ = shortname ? _fbb.CreateString(shortname) : 0;
  return meta::CreateSite(
      _fbb,
      name__,
      shortname__);
}

flatbuffers::Offset<Site> CreateSite(flatbuffers::FlatBufferBuilder &_fbb, const SiteT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DataT : public flatbuffers::NativeTable {
  typedef Data TableType;
  std::vector<std::unique_ptr<UserT>> users;
  std::vector<std::unique_ptr<SiteT>> sites;
  DataT() {
  }
};

struct Data FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef DataT NativeTableType;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USERS = 4,
    VT_SITES = 6
  };
  const flatbuffers::Vector<flatbuffers::Offset<User>> *users() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<User>> *>(VT_USERS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<Site>> *sites() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Site>> *>(VT_SITES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_USERS) &&
           verifier.VerifyVector(users()) &&
           verifier.VerifyVectorOfTables(users()) &&
           VerifyOffset(verifier, VT_SITES) &&
           verifier.VerifyVector(sites()) &&
           verifier.VerifyVectorOfTables(sites()) &&
           verifier.EndTable();
  }
  DataT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DataT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Data> Pack(flatbuffers::FlatBufferBuilder &_fbb, const DataT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DataBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_users(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<User>>> users) {
    fbb_.AddOffset(Data::VT_USERS, users);
  }
  void add_sites(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Site>>> sites) {
    fbb_.AddOffset(Data::VT_SITES, sites);
  }
  explicit DataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  DataBuilder &operator=(const DataBuilder &);
  flatbuffers::Offset<Data> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Data>(end);
    return o;
  }
};

inline flatbuffers::Offset<Data> CreateData(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<User>>> users = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Site>>> sites = 0) {
  DataBuilder builder_(_fbb);
  builder_.add_sites(sites);
  builder_.add_users(users);
  return builder_.Finish();
}

inline flatbuffers::Offset<Data> CreateDataDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<User>> *users = nullptr,
    const std::vector<flatbuffers::Offset<Site>> *sites = nullptr) {
  auto users__ = users ? _fbb.CreateVector<flatbuffers::Offset<User>>(*users) : 0;
  auto sites__ = sites ? _fbb.CreateVector<flatbuffers::Offset<Site>>(*sites) : 0;
  return meta::CreateData(
      _fbb,
      users__,
      sites__);
}

flatbuffers::Offset<Data> CreateData(flatbuffers::FlatBufferBuilder &_fbb, const DataT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline UserT *User::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = new UserT();
  UnPackTo(_o, _resolver);
  return _o;
}

inline void User::UnPackTo(UserT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); };
  { auto _e = username(); if (_e) _o->username = _e->str(); };
  { auto _e = mac(); if (_e) _o->mac = _e->str(); };
  { auto _e = site(); _o->site = _e; };
}

inline flatbuffers::Offset<User> User::Pack(flatbuffers::FlatBufferBuilder &_fbb, const UserT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateUser(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<User> CreateUser(flatbuffers::FlatBufferBuilder &_fbb, const UserT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const UserT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _username = _o->username.empty() ? 0 : _fbb.CreateString(_o->username);
  auto _mac = _o->mac.empty() ? 0 : _fbb.CreateString(_o->mac);
  auto _site = _o->site;
  return meta::CreateUser(
      _fbb,
      _name,
      _username,
      _mac,
      _site);
}

inline SiteT *Site::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = new SiteT();
  UnPackTo(_o, _resolver);
  return _o;
}

inline void Site::UnPackTo(SiteT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); };
  { auto _e = shortname(); if (_e) _o->shortname = _e->str(); };
}

inline flatbuffers::Offset<Site> Site::Pack(flatbuffers::FlatBufferBuilder &_fbb, const SiteT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSite(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Site> CreateSite(flatbuffers::FlatBufferBuilder &_fbb, const SiteT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const SiteT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _shortname = _o->shortname.empty() ? 0 : _fbb.CreateString(_o->shortname);
  return meta::CreateSite(
      _fbb,
      _name,
      _shortname);
}

inline DataT *Data::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = new DataT();
  UnPackTo(_o, _resolver);
  return _o;
}

inline void Data::UnPackTo(DataT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = users(); if (_e) { _o->users.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->users[_i] = std::unique_ptr<UserT>(_e->Get(_i)->UnPack(_resolver)); } } };
  { auto _e = sites(); if (_e) { _o->sites.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->sites[_i] = std::unique_ptr<SiteT>(_e->Get(_i)->UnPack(_resolver)); } } };
}

inline flatbuffers::Offset<Data> Data::Pack(flatbuffers::FlatBufferBuilder &_fbb, const DataT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateData(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Data> CreateData(flatbuffers::FlatBufferBuilder &_fbb, const DataT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const DataT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _users = _o->users.size() ? _fbb.CreateVector<flatbuffers::Offset<User>> (_o->users.size(), [](size_t i, _VectorArgs *__va) { return CreateUser(*__va->__fbb, __va->__o->users[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _sites = _o->sites.size() ? _fbb.CreateVector<flatbuffers::Offset<Site>> (_o->sites.size(), [](size_t i, _VectorArgs *__va) { return CreateSite(*__va->__fbb, __va->__o->sites[i].get(), __va->__rehasher); }, &_va ) : 0;
  return meta::CreateData(
      _fbb,
      _users,
      _sites);
}

inline const meta::Data *GetData(const void *buf) {
  return flatbuffers::GetRoot<meta::Data>(buf);
}

inline const meta::Data *GetSizePrefixedData(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<meta::Data>(buf);
}

inline bool VerifyDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<meta::Data>(nullptr);
}

inline bool VerifySizePrefixedDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<meta::Data>(nullptr);
}

inline void FinishDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<meta::Data> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<meta::Data> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<DataT> UnPackData(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<DataT>(GetData(buf)->UnPack(res));
}

}  // namespace meta

#endif  // FLATBUFFERS_GENERATED_META_META_H_
