// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: nav.capnp

#ifndef CAPNP_INCLUDED_a6eac0a6d72898a3_
#define CAPNP_INCLUDED_a6eac0a6d72898a3_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 6000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(996d72726f728df4);
CAPNP_DECLARE_SCHEMA(8e2bf1c73aaad8d1);
enum class Command_8e2bf1c73aaad8d1: uint16_t {
  UNKNOWN,
  DOWN,
  UP,
  LEFT,
  RIGHT,
  ENTER,
};
CAPNP_DECLARE_ENUM(Command, 8e2bf1c73aaad8d1);
CAPNP_DECLARE_SCHEMA(f7995f58daf6ddee);
CAPNP_DECLARE_SCHEMA(e0786fefa13dfc96);
enum class Page_e0786fefa13dfc96: uint16_t {
  MAIN,
  SETTINGS_ENTRY,
  TRADE_ENTRY,
  FLEET_ENTRY,
  LAUNCH_ENTRY,
  SETTINGS_CHANGE_NAME,
  SETTINGS_SELECT_USER,
  SETTINGS_RESET,
  SHIP_DETAILS,
  SHIP_MISSION_SELECT,
  SHIP_DEST_SELECT,
  SHIP_CONFIRM,
  SHIP_SPLASH,
  SHIP_RENAME,
  EVENT_SHIP_VISIT,
  EVENT_PLAYER_LAUNCH,
  SHIP_VISIT_DECISION,
  SHIP_VISIT_OUTCOME,
  LAUNCH_SPLASH,
  NO_OP,
};
CAPNP_DECLARE_ENUM(Page, e0786fefa13dfc96);

}  // namespace schemas
}  // namespace capnp

namespace nav {

static constexpr  ::uint8_t CMD_NUM = 5u;
typedef ::capnp::schemas::Command_8e2bf1c73aaad8d1 Command;

static constexpr  ::uint8_t PAGE_NUM = 19u;
typedef ::capnp::schemas::Page_e0786fefa13dfc96 Page;

// =======================================================================================

// =======================================================================================

}  // namespace

#endif  // CAPNP_INCLUDED_a6eac0a6d72898a3_
